name: fitment
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  eva_icons_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/appIcons/
  - assets/categoryIcons/
  - assets/tabBarIcons/
  fonts:
  - family: QS-R
    fonts:
    - asset: fonts/Quicksand-Regular.ttf
  - family: QS-M
    fonts:
    - asset: fonts/Quicksand-Medium.ttf  
