name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - name: Setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: Setup Dart ${{ matrix.dart-version }}
      uses: DanTup/gh-actions/setup-dart@master
    - name: Setup Flutter ${{ matrix.flutter-version }}
      id: flutter
      uses: DanTup/gh-actions/setup-flutter@master
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
