name: Flutter Score Analysis

on:
  push:
    branches: 
      - master

jobs:
  package-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: axel-op/dart-package-analyzer/with-full-sdk@stable
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
